name: Python (CPython)

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: "windows-latest"
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.9, "3.10"]
        architecture: [x64, x86]
    steps:
      - name: Check out source
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install pip setuptools wheel --upgrade
      - name: Create wheel
        run: |
          python -m pip wheel . --no-deps --wheel-dir=./wheelhouse/ -vv
      - name: Install package
        run: |
          python -m pip install iteration_utilities --no-index --find-links=./wheelhouse/ -vv
      - name: Import package
        run: |
          python -c "import iteration_utilities"
      - name: Install test dependencies
        run: |
          python -m pip install pytest
      - name: Run tests
        run: |
          python -m pytest tests/
      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: py${{ matrix.python-version }}-${{ matrix.architecture }}-windows-latest
          path: ./wheelhouse/

  bundle-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: py3.9-x64-windows-latest
          path: ./wheels
      - uses: actions/download-artifact@v2
        with:
          name: py3.9-x86-windows-latest
          path: ./wheels
      - uses: actions/download-artifact@v2
        with:
          name: py3.10-x64-windows-latest
          path: ./wheels
      - uses: actions/download-artifact@v2
        with:
          name: py3.10-x86-windows-latest
          path: ./wheels
      - name: Upload all
        uses: actions/upload-artifact@v2
        with:
          name: all
          path: ./
